"""sync models

Revision ID: 13c19b6981d0
Revises: f44364873f24
Create Date: 2026-07-29 01:48:51.146828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c19b6981d0'
down_revision: Union[str, Sequence[str], None] = 'f44364873f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('parser_method', sa.String(length=50), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statements_user_id'), 'statements', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('statement_id', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('debit', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('credit', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('payment_mode', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('transaction_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_transactions_statement_id'), 'transactions', ['statement_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_hash'), 'transactions', ['transaction_hash'], unique=True)
    op.create_foreign_key(None, 'transactions', 'statements', ['statement_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_transaction_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_statement_id'), table_name='transactions')
    op.drop_column('transactions', 'transaction_hash')
    op.drop_column('transactions', 'payment_mode')
    op.drop_column('transactions', 'balance')
    op.drop_column('transactions', 'credit')
    op.drop_column('transactions', 'debit')
    op.drop_column('transactions', 'statement_id')
    op.drop_index(op.f('ix_statements_user_id'), table_name='statements')
    op.drop_table('statements')
    # ### end Alembic commands ###
