"""update budget model

Revision ID: cda76c291e59
Revises: 13c19b6981d0
Create Date: 2026-07-29 12:08:29.099801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cda76c291e59'
down_revision: Union[str, Sequence[str], None] = '13c19b6981d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('month', sa.Integer(), nullable=False))
    op.add_column('budgets', sa.Column('year', sa.Integer(), nullable=False))
    op.alter_column('budgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('budgets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_budgets_category'), 'budgets', ['category'], unique=False)
    op.create_index(op.f('ix_budgets_month'), 'budgets', ['month'], unique=False)
    op.create_index(op.f('ix_budgets_year'), 'budgets', ['year'], unique=False)
    op.create_unique_constraint('uq_budget_user_category_month_year', 'budgets', ['user_id', 'category', 'month', 'year'])
    op.alter_column('transactions', 'statement_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'statement_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('uq_budget_user_category_month_year', 'budgets', type_='unique')
    op.drop_index(op.f('ix_budgets_year'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_month'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_category'), table_name='budgets')
    op.alter_column('budgets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('budgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('budgets', 'year')
    op.drop_column('budgets', 'month')
    # ### end Alembic commands ###
